name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: (cd seminar && zip -r ../deploy.zip .)
    
    - name: Declare variables
      id: vars
      shell: bash
      run: |
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: first_feedpage
        environment_name: FirstFeedpage-env
        region: ap-northeast-2
        version_label: ${{ steps.vars.outputs.sha }}
        deployment_package: deploy.zip
